### ISSUE TITLE
Getting RA DEC for the objects.

### ISSUE THREAD

**Issue by 29satnam** [silvinaroldan/SwissEphemeris#1]
Hey, this library looks just great but I can't figure out how'd I get RA/DEC for an object. I ran your test project but I couldn't find a way to get coordinates.

**Comment by silvinaroldan** [comment]
Hey @29satnam, sorry it has taken so long for me to answer. Maybe you already figured it but
I've already added the code and the example to get the Right Ascension in radians and the Declination in degrees.
You could double check it [here](http://www.astro.com/swisseph/swetest.htm) with this option `PLBRSaD` :

<img width="550" alt="Screen Shot 2020-05-08 at 23 56 43" src="https://user-images.githubusercontent.com/8246422/81462295-e95cb180-9187-11ea-978e-645298f2318c.png">

**Comment by 29satnam** [comment]
> Hey @29satnam, sorry it has taken so long for me to answer. Maybe you already figured it but
> I've already added the code and the example to get the Right Ascension in radians and the Declination in degrees.
> You could double check it [here](http://www.astro.com/swisseph/swetest.htm) with this option `PLBRSaD` :
> 
> <img alt="Screen Shot 2020-05-08 at 23 56 43" width="550" src="https://user-images.githubusercontent.com/8246422/81462295-e95cb180-9187-11ea-978e-645298f2318c.png">

Hey! I don't even remember what i did back then!
Thank you though! :D

**Comment by silvinaroldan** [comment]
> Hey! I don't even remember what i did back then!
> Thank you though! :D

Yeah, it has been a long time since you asked. YW! 😉
